/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container': '#f1f5f9',
        'surface-container-low': '#f8fafc',
        'background': '#f8fafc',
        'secondary': '#2563eb',
        'surface-variant': '#e2e8f0',
        'on-secondary-fixed': '#1e3a8a',
        'on-primary-container': '#1e3a8a',
        'on-error': '#ffffff',
        'on-background': '#0f172a',
        'tertiary': '#334155',
        'inverse-primary': '#93c5fd',
        'on-tertiary-container': '#475569',
        'outline-variant': '#cbd5e1',
        'on-primary-fixed-variant': '#1e40af',
        'primary': '#1e3a8a',
        'surface-dim': '#e2e8f0',
        'on-primary': '#ffffff',
        'surface-bright': '#ffffff',
        'primary-fixed-dim': '#93c5fd',
        'on-secondary-container': '#1e3a8a',
        'inverse-surface': '#1e293b',
        'on-tertiary': '#ffffff',
        'on-surface': '#0f172a',
        'surface-container-lowest': '#ffffff',
        'primary-fixed': '#dbeafe',
        'tertiary-container': '#f1f5f9',
        'on-surface-variant': '#475569',
        'on-secondary-fixed-variant': '#1d4ed8',
        'primary-container': '#dbeafe',
        'surface': '#ffffff',
        'on-secondary': '#ffffff',
        'tertiary-fixed-dim': '#cbd5e1',
        'on-tertiary-fixed-variant': '#475569',
        'error-container': '#fee2e2',
        'secondary-container': '#bfdbfe',
        'on-tertiary-fixed': '#0f172a',
        'surface-container-highest': '#e2e8f0',
        'surface-container-high': '#f1f5f9',
        'secondary-fixed-dim': '#93c5fd',
        'outline': '#94a3b8',
        'secondary-fixed': '#dbeafe',
        'error': '#dc2626',
        'on-error-container': '#991b1b',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'container-max': '1280px',
        'lg': '32px',
        'xl': '48px',
        'md': '24px',
        'sm': '16px',
        'xs': '8px',
        'gutter': '24px',
        'base': '4px',
      },
      fontFamily: {
        'body-sm': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}