/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container': '#e7eeff',
        'background': '#f9f9ff',
        'secondary': '#1960a3',
        'surface-variant': '#d8e3fa',
        'on-secondary-fixed': '#001c38',
        'on-primary-container': '#86a0cd',
        'on-error': '#ffffff',
        'on-background': '#111c2c',
        'tertiary': '#1b2127',
        'inverse-primary': '#adc7f7',
        'on-tertiary-container': '#989fa6',
        'outline-variant': '#c4c6cf',
        'on-primary-fixed-variant': '#2d476f',
        'primary': '#002045',
        'surface-dim': '#cfdaf1',
        'on-primary': '#ffffff',
        'surface-bright': '#f9f9ff',
        'primary-fixed-dim': '#adc7f7',
        'on-secondary-container': '#00477f',
        'inverse-surface': '#263142',
        'on-tertiary': '#ffffff',
        'on-surface': '#111c2c',
        'surface-container-lowest': '#ffffff',
        'primary-fixed': '#d6e3ff',
        'tertiary-container': '#30363c',
        'on-surface-variant': '#43474e',
        'on-secondary-fixed-variant': '#004881',
        'primary-container': '#1a365d',
        'surface': '#f9f9ff',
        'on-secondary': '#ffffff',
        'tertiary-fixed-dim': '#c1c7cf',
        'on-tertiary-fixed-variant': '#41474e',
        'error-container': '#ffdad6',
        'secondary-container': '#7db6ff',
        'on-tertiary-fixed': '#161c22',
        'surface-container-highest': '#d8e3fa',
        'surface-container-high': '#dee8ff',
        'secondary-fixed-dim': '#a2c9ff',
        'outline': '#74777f',
        'secondary-fixed': '#d3e4ff',
        'error': '#ba1a1a',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'container-max': '1280px',
        'lg': '32px',
        'xl': '48px',
        'md': '24px',
        'sm': '16px',
        'xs': '8px',
        'gutter': '24px',
        'base': '4px',
      },
      fontFamily: {
        'body-sm': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}